version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ucatec
      MYSQL_DATABASE: exampledb
      MYSQL_USER: ives_alfaro
      MYSQL_PASSWORD: examplepassword
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: examplepassword

volumes:
  db_data:
